### ISSUE TITLE
homework for concurrent programming study

### ISSUE THREAD

**Issue by jihoon-ko** [kaist-cp/kaist-cp#3]
3/23
- orderings: relaxed, release, acquire
- operators: read, write, update(read-modify-write), fences(release fence / acquire fence / SC fence)

Homework (~ 3/30)
- optimizations in paper
- "DRF Theorem"
- "Java Causality Test Case"  (optional, but recommended)
- Trieber stack

**Comment by jihoon-ko** [comment]
Does "Java Causality Test Case" mean http://www.cs.umd.edu/~pugh/java/memoryModel/CausalityTestCases.html ?

**Comment by jeehoonkang** [comment]
@jihoon-ko yeah, right.  Thanks!

**Comment by tomtomjhj** [comment]
https://people.mpi-sws.org/~viktor/wmc/
