### ISSUE TITLE
구매 및 연구실 환경 정리

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/kaist-cp#9]
## 구매

- [x] 책상/의자
- [x] 프린터
- [x] 모니터
- [ ] 데스크탑
- [ ] 키보드
- [ ] 휴지 등 필요한 비품

## 환경 정리

- [ ] 학생 방에 신발 벗고 들어가기?
- [ ] 자리 배치
- [ ] 화이트보드 셋업
- [ ] 화의실 셋업

**Comment by tomtomjhj** [comment]
![](https://i.imgur.com/YQOmnCd.jpg)

**Comment by drzix** [comment]
## 구매

- [x] 책상
- [ ] 의자 : @drzix 가 적절한 것을 찾아보도록 함. 
- [ ] 프린터
- [ ] 모니터 : 추가 구매 예정.
- [ ] 데스크탑 : AMD 새 버전이 나오면 추가 구매 예정.
- [ ] 키보드 : 추가 구매 예정.
- [x] 마우스
- [ ] 가비지콜렉통 : 임의로 빈 박스를 사용 중.
- [ ] 휴지 등 필요한 비품

## 환경 정리
- [ ] 학생 방에 신발 벗고 들어가기?
- [ ] 자리 배치
- [ ] 화이트보드 셋업
- [ ] 회의실

**Comment by jeehoonkang** [comment]
모니터/키보드 주문 했습니다.

**Comment by jeehoonkang** [comment]
일단 이 이슈는 닫고, 필요한 물품이 있으면 물품별로 issue 만들어주시길 부탁드립니다.
